tap "1password/tap"
tap "aws/tap"
tap "common-fate/granted"
tap "equinix/homebrew-tap"
tap "farmotive/k8s"
tap "fluxcd/tap"
tap "future-architect/tap"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask", "git@github.com:Homebrew/homebrew-cask.git"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "yt-dlp/taps"
brew "act", args: ["HEAD"]
brew "asciinema"
brew "autoconf"
brew "awscli"
brew "python@3.10"
brew "autojump"
brew "automake"
brew "bat" # cat with syntax highlighting 👌
brew "bats-core"
brew "glib"
brew "boxes"
brew "calc"
brew "cfssl"
brew "chart-testing"
brew "cilium-cli"
brew "cmake"
brew "consul-template"
brew "cowsay"
brew "eks-anywhere"
brew "fd"
brew "gawk"
brew "glab"
brew "gnu-sed"
brew "grep"
brew "graphviz"
brew "common-fate/granted/granted"
brew "ctags"
brew "curl"
brew "direnv"
brew "gnutls"
brew "gpg2"
brew "ffmpeg"
brew "figlet"
brew "fluxcd/tap/flux@0.41" # pin below v2 for work
brew "fswatch"
brew "fzf"
# brew "gcc"
brew "gh"
brew "git"
brew "git-lfs"
# we already install gpg2
# brew "gnupg"
brew "helm"
brew "hexyl"
brew "htop"
brew "httpie"
# brew "imagemagick"
brew "influxdb@1"
brew "jfrog-cli"
brew "jinja2-cli"
brew "just"
brew "k3d"
brew "k9s"
brew "kcat"
brew "kdoctor"
brew "kpoof"
brew "kubectx"
brew "kustomize"
# linux vms on mac
brew "lima"
brew "logcli"
brew "lolcat"
brew "luarocks"
brew "ubuntu/microk8s/microk8s"
brew "metal-cli"
brew "mongosh"
brew "mysql-client"
# ng docker-like cli for mac
# brew "nerdctl"
brew "neovim", args: ["HEAD"]
brew "nghttp2"
brew "ninja"
brew "nmap"
brew "node"
brew "nvm"
brew "nyancat"
# brew "open-ocd", args: ["HEAD"]
# cask "openlens"
brew "openssh"
brew "operator-sdk"
brew "parallel"
brew "packer"
brew "pcalc"
brew "perl"
brew "pigz"
brew "pinentry-mac"
brew "pipenv"
brew "pipx"
# brew "platformio"
brew "pnpm"
brew "ponysay"
brew "derailed/popeye/popeye"
brew "postgresql@14"
brew "pre-commit"
brew "pv"
brew "pwgen"
brew "pyenv"
brew "python-yq"
brew "qemu"
brew "rancher-cli"
brew "reattach-to-user-namespace"
brew "redis"
brew "ripgrep"
brew "rsync"
brew "rust-analyzer"
brew "shellcheck"
brew "sponge"
# brew "squashfs"
# brew "stlink"
brew "stern"
brew "teleport"
brew "tfenv"
brew "tftarget"
# brew "the_silver_searcher"
brew "tilt"
brew "tio"
brew "tmux"
brew "toilet"
brew "tree"
# brew "vagrant-completion"
brew "vim"
brew "watch"
brew "wget"
brew "yamllint"
brew "yarn"
brew "youtube-dl"
brew "yq"
# leave this to tfenv
# brew "hashicorp/tap/terraform", link: false
brew "yt-dlp/taps/yt-dlp"
cask "1password-cli"
cask "android-sdk"
cask "bloomrpc"
cask "font-fira-code-nerd-font"
# cask "gcc-arm-embedded"
cask "insomnia"
cask "key-codes"
# cask "openscad"
# cask "vagrant"
# cask "virtualbox"
# cask "virtualbox-extension-pack"
# cask "vlc"
# cask "wireshark"
