#!/usr/bin/env zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export EDITOR=nvim

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH="$PATH:/usr/local/go/bin:${HOME}/bc/infrastructure/scripts:/usr/local/opt/influxdb@1/bin:${HOME}/bin:$(go env GOPATH)/bin:${HOME}/Library/Python/3.9/bin"

if [ -d "${HOME}/.local/bin" ]; then
    export PATH="${PATH}:${HOME}/.local/bin"
fi

SRE_SCRIPTS="${HOME}/bc/sre/sre-scripts"
if [ -d "$SRE_SCRIPTS" ]; then
	export PATH="${PATH}:$SRE_SCRIPTS"
fi

export GEM_HOME="$HOME/.gem"

# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="robbyrussell"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

export ZSH_TMUX_AUTOSTART=true
export ZSH_TMUX_AUTOCONNECT=false
export ZSH_TMUX_AUTOQUIT=false

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    aws
	brew
	direnv
	docker
	fzf
	gcloud
	github
	golang
	ipfs
    kubectl
    kubectx
	nmap
	nomad
	npm
	nvm
	pip
	rust
	salt
	terraform
	vagrant
	vault
	virtualenv
	git
	tmux
	vi-mode
    yarn
	zsh-autosuggestions
	zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration

if [ -f "${HOME}/.zsh_secrets" ]; then
	. "${HOME}/.zsh_secrets"
fi

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

#                        __          __    ___      
#                       /\ \        /\ \__/\_ \     
#   ___      __   _ __  \_\ \    ___\ \ ,_\//\ \    
# /' _ `\  /'__`\/\`'__\/'_` \  /'___\ \ \/ \ \ \   
# /\ \/\ \/\  __/\ \ \//\ \L\ \/\ \__/\ \ \_ \_\ \_ 
# \ \_\ \_\ \____\\ \_\\ \___,_\ \____\\ \__\/\____\
#  \/_/\/_/\/____/ \/_/ \/__,_ /\/____/ \/__/\/____/
#                                                   
#                                                   
if command -v lima &> /dev/null; then
        alias docker="lima nerdctl"
fi
alias alpinism='docker run --privileged=true -v $(pwd):/summit -it alpine'
alias code="open -a 'Visual Studio Code'"
alias gcob='git branch -a | fzf | xargs git checkout'
alias gpsh='git push origin HEAD'
alias gupstr='git branch {--set-upstream-to=origin/,}$(git branch --show-current)'
alias gpl='git pull'
alias ghprcp='gh pr view --json url | jq -r .url | pbcopy'
alias k="kubectl"
complete -F __start_kubectl k
alias kctx="kubetcx"
alias kns="kubens"

if command -v nvim &> /dev/null; then
        # life is worth living
        alias vi="nvim"
        alias vim="nvim"
fi
#  ____  __.__.__  .__                       
# |    |/ _|__|  | |  |   ___________  ______
# |      < |  |  | |  | _/ __ \_  __ \/  ___/
# |    |  \|  |  |_|  |_\  ___/|  | \/\___ \ 
# |____|__ \__|____/____/\___  >__|  /____  >
#         \/                 \/           \/ 
alias dkill="docker ps | sed -e '1d' | fzf -m | awk '{ print \$1 }' | xargs docker kill"
alias tmkill='tmux list-sessions | fzf -m | awk -F: "{ print \$1 }" | while read sess; do tmux kill-session -t "$sess"; done'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '${HOME}/lib/google-cloud-sdk/path.zsh.inc' ]; then . '${HOME}/lib/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '${HOME}/lib/google-cloud-sdk/completion.zsh.inc' ]; then . '${HOME}/lib/google-cloud-sdk/completion.zsh.inc'; fi

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

if [ -f "${HOME}/.zephyrrc" ]; then . "${HOME}/.zephyrrc"; fi

if [ -f "${HOME}/export-esp.sh" ]; then . "${HOME}/export-esp.sh"; fi

if [ -e ${HOME}/.nix-profile/etc/profile.d/nix.sh ]; then . ${HOME}/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
