#!/usr/bin/env bash

set -euo pipefail

REPO_DIRS=()
REPO_DIRS_CONFIG="${HOME}/.config/sessionizer/dirs"
if [ ! -s "$REPO_DIRS_CONFIG" ]; then
    mkdir -p "$(dirname "$REPO_DIRS_CONFIG")"
    chezmoi source-path >> "$REPO_DIRS_CONFIG"
fi
if [ -f "$REPO_DIRS_CONFIG" ]; then
    # :'( only bash >= 4.4
    # mapfile -t REPO_DIRS < "$REPO_DIRS_CONFIG"
    # export REPO_DIRS
    REPO_DIRS=()
    while IFS='' read -r line; do
        REPO_DIRS+=("$line");
    done < "$REPO_DIRS_CONFIG"
    export REPO_DIRS
fi

# speed up with some parallelization
printf '%s\n' "${REPO_DIRS[@]/#\~/${HOME}}" \
    | xargs -P "${#REPO_DIRS[@]}" -I{} fd \
    --type d \
    --exclude '**/.terraform/**' \
    -H --print0 \
    .git {} | xargs -0 dirname
