#!/usr/bin/env bash

set -euo pipefail

FILENAME="screenshot-`date +%F-%T`"
TARGET_DIR="${XDG_PICTURES_DIR:-${HOME}/Pictures}"
mkdir -p "${TARGET_DIR}"
grim -g "$(slurp)" "${TARGET_DIR}/${FILENAME}.png"
