#!/usr/bin/env bash

set -euo pipefail

MODE=${1:-"partial"}

FILENAME="screenshot-`date +%F-%T`"
TARGET_DIR="${XDG_PICTURES_DIR:-${HOME}/Pictures}"
mkdir -p "${TARGET_DIR}"

if [ "$MODE" = "full" ]; then
    grim "${TARGET_DIR}/${FILENAME}.png"
else
    grim -g "$(slurp)" "${TARGET_DIR}/${FILENAME}.png"
fi
