#!/usr/bin/env bash

BROWSER="${BROWSER:-"xdg-open"}"

BOOKMARKS="$(pocket-get | jq ".list | to_entries | map({id: .value.item_id, url: .value.resolved_url, title: .value.resolved_title})")"

REPRS="$(jq -r ".[] | .title + \" \" + .url" <<< "$BOOKMARKS" | sed -e 's/^\s*//')"

PAGE="$(fzf <<< "$REPRS" | awk '{ print $NF }')"

if [ -n "$PAGE" ]; then
    "$BROWSER" "$PAGE" 2>/dev/null
fi
