#!/usr/bin/env bash

#           _       
#    _     | |      
#  _| |_ __| | ____ 
# (_   _) _  |/ ___)
#   | |( (_| ( (___ 
#    \__)____|\____)
#                   
#   - teleport database connect

set -euo pipefail

DB_USER="${DB_USER:-"infra-team"}"

DB="$(tsh db ls -fjson \
    | jq -r '.[]|.metadata.name' \
    | fzf)"

tsh db login "$DB"
tsh db connect --db-user="$DB_USER" "$DB"
