#!/usr/bin/env bash

#                                              
# @@@  @@@  @@@  @@@  @@@  @@@       @@@       
# @@@  @@@  @@@  @@@  @@@  @@@       @@@       
# @@!  !@@  @@!  !@@  @@!  @@!       @@!       
# !@!  @!!  !@!  @!!  !@!  !@!       !@!       
# @!@@!@!   @!@@!@!   !!@  @!!       @!!       
# !!@!!!    !!@!!!    !!!  !!!       !!!       
# !!: :!!   !!: :!!   !!:  !!:       !!:       
# :!:  !:!  :!:  !:!  :!:   :!:       :!:      
#  ::  :::   ::  :::   ::   :: ::::   :: ::::  
#  :   :::   :   :::  :    : :: : :  : :: : :  
#                                              
#    k8s pod killer

set -euo pipefail

SELECTION="$(kubectl get pods -A \
    | sed '1d' \
    | fzf -m \
    | awk '{ print $1,$2 }'
)"

while read -r NS POD; do
    kubectl delete -n "$NS" pod "$POD" "$@"
done <<< "$SELECTION"
